[tool.poetry]
name = "MITHRA"
version = "0.1.0"
description = "A wrapper for stellar evolution models and tracks."
authors = ["Harrison Nicholls <harrison.nicholls@physics.ox.ac.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.dev-dependencies]
pytest = "^6.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

